# show sql statements issued by JPA
spring.jpa.show-sql=true

# enable debug logging for spring boot and hibernate classes
# this is equivalent to passing '--debug' as command line argument
#logging.level.org.springframework.boot=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

# Database Lab61
spring.datasource.url=jdbc:mysql://172.16.0.30:3306/hpds_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=hpds
spring.datasource.password=2diSenai
